from pathlib import Path

p = Path('src/app.js')
s = p.read_text(encoding='utf-8')

def replace_once(old, new, label):
    global s
    if old not in s:
        raise SystemExit(f'missing anchor: {label}')
    s = s.replace(old, new, 1)

replace_once(
"let state=loadState(), currentPage='home', selectedGrowthHero='player', selectedGrowthTab='meridian';",
"let state=loadState(), currentPage='home', selectedGrowthHero='player', selectedGrowthTab='meridian', heroFilter='all', heroDetailId=null;",
'hero ui state'
)

old = '''function renderHeroes(){const ids=Object.keys(HEROES).sort((a,b)=>{const ao=state.heroes[a]?.owned?1:0,bo=state.heroes[b]?.owned?1:0;if(ao!==bo)return bo-ao;if(HEROES[a].unlock!==HEROES[b].unlock)return HEROES[a].unlock-HEROES[b].unlock;return HEROES[b].rarity-HEROES[a].rarity;});pageEl.innerHTML=`<div class="section-title"><h2>侠客</h2><small>${ids.filter(id=>state.heroes[id]?.owned).length}/${ids.length}</small></div><div class="notice">已接入侠客升级、上阵/下阵、传奇令定向招募、经脉与功法战力。</div><div class="hero-list" style="margin-top:10px">${ids.map(heroCard).join('')}</div>`;}'''
new = '''const HERO_FILTERS=[['all','全部'],['owned','已拥有'],['god','神品'],['legend','传奇'],['master','宗师'],['locked','未获得']];
function heroMatchesFilter(id){const owned=!!state.heroes[id]?.owned,rarity=Number(profileOf(id)?.rarity||HEROES[id]?.rarity||0);if(heroFilter==='owned')return owned;if(heroFilter==='locked')return !owned;if(heroFilter==='god')return rarity>=7;if(heroFilter==='legend')return rarity===6;if(heroFilter==='master')return rarity===5;return true;}
function skillTargetText(target){return {all:'敌方全体',three:'敌方3人',highestAtk:'敌方攻击最高',one:'敌方单体'}[target]||'敌方单体';}
function heroAcquireText(id){const base=HEROES[id],h=state.heroes[id];if(h?.owned)return state.party.includes(id)?'已拥有 · 已上阵':'已拥有 · 未上阵';if(base.recruit?.type==='vip8')return 'VIP8后购买40888元宝专属礼包';if(base.recruit?.type==='legendToken')return `第${base.unlock}幕 · ${fmt(base.recruit.cost)}传奇招募令`;if(base.recruit?.type==='special')return `第${base.unlock}幕 · ${base.recruit.item}×${fmt(base.recruit.cost)}`;if(id==='xiaozhao')return '首充6元获得';return base.unlock?`第${base.unlock}幕开放`:'初始/剧情获得';}
function heroSkillDetail(tpl){const sk=tpl?.skill||{},parts=[`${sk.name||'绝技'} · ${skillTargetText(sk.target)} · ${Number(sk.multiplier||1).toFixed(2)}倍`,`${Number(sk.rageCost||4)}怒`];if(sk.teamRage)parts.push(`全队回怒+${sk.teamRage}`);if(sk.healTeam)parts.push(`全队治疗系数${Math.round(sk.healTeam*100)}%`);if(sk.refundOnKill)parts.push('击杀返还绝技怒气');if(sk.repeatChance)parts.push(`连发概率${Math.round(sk.repeatChance*100)}%`);if(sk.ignoreDef)parts.push(`穿防${Math.round(sk.ignoreDef*100)}%`);if(Array.isArray(sk.abnormal))parts.push(...sk.abnormal.map(x=>`${{stun:'眩晕',silence:'沉默',seal:'封穴'}[x.type]||'异常'}${Math.round(Number(x.chance||0)*100)}%`));return parts.join(' · ');}
function heroDetailHtml(id){if(!id||!HEROES[id])return '';const base=HEROES[id],tpl=profileOf(id),h=state.heroes[id],owned=!!h?.owned,s=owned?heroStats(state,id):null,baseStats=tpl?.base||base.base||{},extras=[];if(tpl?.passive?.firstRoundAbnormalImmune)extras.push('首回合免疫异常');if(tpl?.combat?.buddhaNormal)extras.push(`普攻佛性+${tpl.combat.buddhaNormal}`);if(tpl?.combat?.buddhaSkill)extras.push(`绝技佛性+${tpl.combat.buddhaSkill}`);if(tpl?.combat?.vajraGuardOnSkill)extras.push('绝技开启金刚伏魔圈护盾');const awaken=awakeningConfig(id);return `<section class="card"><div class="section-title"><div><span class="tag">侠客详情</span><h3 class="rarity-${tpl.rarity}">${tpl.name}</h3></div><button class="btn" data-hero-detail="${id}">收起</button></div><div class="hero-meta">${rarityName(tpl.rarity)} · ${tpl.role} · ${heroAcquireText(id)}</div><div class="grid-2" style="margin-top:10px"><div class="mini-stat"><div class="muted">攻击</div><div class="big-number small">${fmt(s?.atk??baseStats.atk)}</div></div><div class="mini-stat"><div class="muted">防御</div><div class="big-number small">${fmt(s?.def??baseStats.def)}</div></div><div class="mini-stat"><div class="muted">气血</div><div class="big-number small">${fmt(s?.hp??baseStats.hp)}</div></div><div class="mini-stat"><div class="muted">速度</div><div class="big-number small">${fmt(s?.speed??baseStats.speed)}</div></div></div><div class="notice" style="margin-top:10px"><b>${owned?'当前实战属性':'基础模板属性'}</b>。${owned?'已计入等级、经脉、功法、内力、神兵、神品与悟道等当前培养结果。':'获得后会再叠加各养成系统。'}</div><div class="list-row"><span>绝技</span><small>${heroSkillDetail(tpl)}</small></div>${extras.length?`<div class="list-row"><span>机制</span><small>${extras.join(' · ')}</small></div>`:''}${owned?`<div class="list-row"><span>战斗属性</span><small>命中 ${Number(s.hit||0).toFixed(1)}% · 闪避 ${Number(s.dodge||0).toFixed(1)}% · 暴击 ${Number(s.crit||0).toFixed(1)}% · 抗暴 ${Number(s.antiCrit||0).toFixed(1)}%</small></div><div class="list-row"><span>伤害</span><small>增伤 ${Number(s.damageBonus||0).toFixed(1)}% · 减伤 ${Number(s.damageReduction||0).toFixed(1)}% · 初始怒气 ${fmt(s.initialRage||0)}</small></div>`:''}${awaken?`<div class="list-row"><span>神品</span><small>${h?.awakened?awaken.desc:`${awaken.unlockChapter}幕可觉醒 · 当前魂石 ${fmt(state.awakening?.stones?.[id]||0)} · 碎片 ${fmt(state.awakening?.fragments?.[id]||0)}/${SOUL_SHARDS_PER_STONE}`}</small></div>`:''}</section>`;}
function heroListCard(id){return `<div>${heroCard(id)}<button class="btn btn-block ${heroDetailId===id?'btn-gold':''}" data-hero-detail="${id}" style="margin-top:6px">${heroDetailId===id?'收起详情':'查看详情'}</button></div>`;}
function renderHeroes(){const allIds=Object.keys(HEROES).sort((a,b)=>{const ao=state.heroes[a]?.owned?1:0,bo=state.heroes[b]?.owned?1:0;if(ao!==bo)return bo-ao;if(HEROES[a].unlock!==HEROES[b].unlock)return HEROES[a].unlock-HEROES[b].unlock;return HEROES[b].rarity-HEROES[a].rarity;}),ids=allIds.filter(heroMatchesFilter),ownedCount=allIds.filter(id=>state.heroes[id]?.owned).length;pageEl.innerHTML=`<div class="section-title"><h2>侠客</h2><small>${ownedCount}/${allIds.length}</small></div><section class="card"><div class="section-title"><h3>筛选</h3><small>当前 ${ids.length} 名</small></div><div class="action-row" style="flex-wrap:wrap">${HERO_FILTERS.map(([key,label])=>`<button class="btn ${heroFilter===key?'btn-gold':''}" data-hero-filter="${key}">${label}</button>`).join('')}</div></section>${heroDetailHtml(heroDetailId)}<div class="notice">可按拥有状态/品质筛选；详情展示当前实战属性、绝技机制、获取方式和神品进度。</div><div class="hero-list" style="margin-top:10px">${ids.length?ids.map(heroListCard).join(''):'<section class="card"><div class="muted">当前筛选条件下没有侠客。</div></section>'}</div>`;}'''
replace_once(old, new, 'renderHeroes block')

old = "pageEl.addEventListener('click',e=>{const btn=e.target.closest('button');if(!btn)return;if(btn.dataset.pageJump){currentPage=btn.dataset.pageJump;render();return;}if(btn.dataset.growthTab){selectedGrowthTab=btn.dataset.growthTab;renderGrowth();return;}"
new = "pageEl.addEventListener('click',e=>{const btn=e.target.closest('button');if(!btn)return;if(btn.dataset.pageJump){currentPage=btn.dataset.pageJump;render();return;}if(btn.dataset.heroFilter){heroFilter=btn.dataset.heroFilter;heroDetailId=null;renderHeroes();return;}if(btn.dataset.heroDetail){heroDetailId=heroDetailId===btn.dataset.heroDetail?null:btn.dataset.heroDetail;renderHeroes();return;}if(btn.dataset.growthTab){selectedGrowthTab=btn.dataset.growthTab;renderGrowth();return;}"
replace_once(old, new, 'hero click handlers')

p.write_text(s, encoding='utf-8')
print('V0.18 hero UI patch applied')
