from pathlib import Path
p=Path('src/app.js')
s=p.read_text()
old="function buyKungfuTicket(){if(state.player.gems<300)return alert('元宝不足，需要300元宝。');state.player.gems-=300;state.player.kungfuTickets+=1;commit();}\nfunction drawKungfu(){if(state.player.kungfuTickets<1)return alert('没有功法帖。');state.player.kungfuTickets-=1;state.kungfu.drawCount=Number(state.kungfu.drawCount||0)+1;if(Math.random()<.02){const ids=Object.keys(RED_KUNGFU),id=ids[Math.floor(Math.random()*ids.length)];addKungfuCopy(id,1);commit();alert(`藏经阁：获得红色功法【${RED_KUNGFU[id].name}】！`);return;}state.kungfu.fragments=Number(state.kungfu.fragments||0)+1;commit();alert('藏经阁：本次未出红功法，低品质结果折算为功法残页×1。');}"
new="function drawKungfu(times=1){const n=Number(times)===5?5:1,cost=n*300;if(state.player.gems<cost)return alert(`元宝不足，需要${cost}元宝。`);state.player.gems-=cost;const reds=[];let fragments=0;for(let i=0;i<n;i++){state.kungfu.drawCount=Number(state.kungfu.drawCount||0)+1;if(Math.random()<.02){const ids=Object.keys(RED_KUNGFU),id=ids[Math.floor(Math.random()*ids.length)];addKungfuCopy(id,1);reds.push(RED_KUNGFU[id].name);}else{state.kungfu.fragments=Number(state.kungfu.fragments||0)+1;fragments++;}}commit();const redText=reds.length?`红色功法：${reds.map(x=>`【${x}】`).join('、')}`:'未获得红色功法';alert(`藏经阁抽取${n}次：${redText}${fragments?`；功法残页 +${fragments}`:''}。`);}"
assert old in s
s=s.replace(old,new)
marker="function recharge(yuan){"
assert marker in s
inner_funcs=r'''function assignInnerRoom(){if(state.player.chapter<INNER_POWER_OPEN_CHAPTER)return alert(`内力系统第${INNER_POWER_OPEN_CHAPTER}幕开放。`);ensureGrowthHero();if(innerPowerRoomIndex(selectedGrowthHero)>=0)return;const index=(state.innerPower?.rooms||[]).findIndex(x=>!x);if(index<0)return alert('七个练功房都有人。');state.innerPower.rooms[index]=selectedGrowthHero;state.innerPower.lastTick=Date.now();commit();}
function leaveInnerRoom(){ensureGrowthHero();recoverInnerPower(state);const index=innerPowerRoomIndex(selectedGrowthHero);if(index<0)return;state.innerPower.rooms[index]=null;state.innerPower.lastTick=Date.now();commit();}
function useInnerMedicine(key){ensureGrowthHero();const m=INNER_POWER_MEDICINES[key],h=state.heroes[selectedGrowthHero],ip=h?.innerPower;if(!m||!ip)return;const count=Number(state.innerPower?.items?.[key]||0);if(count<=0)return alert(`${m.name}不足。`);if(ip.year<m.minYear||ip.year>m.maxYear)return alert(`${m.name}仅适用于${m.minYear}～${m.maxYear}年。`);if(ip.year>=INNER_POWER_MAX_YEAR)return alert('内力已经达到280年上限。');const used=Number(ip.medicineUsed?.[key]||0),gain=medicinePower(key,used);state.innerPower.items[key]-=1;ip.medicineUsed[key]=used+1;ip.power=Number(ip.power||0)+gain;advanceInnerPower(ip);commit();alert(`${HEROES[selectedGrowthHero].name}服用${m.name}，内力 +${fmt(gain)}。`);}
function attemptInnerBreakthrough(usePill=false){ensureGrowthHero();const ip=state.heroes[selectedGrowthHero]?.innerPower;if(!ip)return;const year=readyBreakthroughYear(ip);if(!year)return alert('当前尚未到十年瓶颈。');const now=Date.now();if(Number(ip.recoveryUntil||0)>now)return alert(`仍在调息，还需${formatRemain(ip.recoveryUntil-now)}。`);const info=breakthroughInfo(year);let rate=info.rateBp;if(usePill){if(Number(state.innerPower?.items?.dingshen||0)<=0)return alert('定神丸不足。');state.innerPower.items.dingshen-=1;rate+=calmingPillRateBonus(year);}rate=Math.min(10000,rate);if(Math.floor(Math.random()*10000)<rate){ip.passed=Array.isArray(ip.passed)?ip.passed:[];if(!ip.passed.includes(year))ip.passed.push(year);ip.year=year;ip.recoveryUntil=0;advanceInnerPower(ip);commit();alert(`突破成功！${HEROES[selectedGrowthHero].name}内力达到${year}年。`);}else{ip.recoveryUntil=Date.now()+info.recoverySec*1000;commit();alert(`突破失败，进入调息 ${formatRemain(info.recoverySec*1000)}。`);}}
'''
s=s.replace(marker,inner_funcs+marker)
s=s.replace("if(action==='buyKungfuTicket')buyKungfuTicket();if(action==='drawKungfu')drawKungfu();", "if(action==='drawKungfu1')drawKungfu(1);if(action==='drawKungfu5')drawKungfu(5);if(action==='assignInnerRoom')assignInnerRoom();if(action==='leaveInnerRoom')leaveInnerRoom();if(action==='innerBreakthrough')attemptInnerBreakthrough(false);if(action==='innerBreakthroughPill')attemptInnerBreakthrough(true);")
s=s.replace("if(btn.dataset.fuseDivine){fuseDivine(btn.dataset.fuseDivine);return;}if(btn.dataset.recharge)", "if(btn.dataset.fuseDivine){fuseDivine(btn.dataset.fuseDivine);return;}if(btn.dataset.innerMedicine){useInnerMedicine(btn.dataset.innerMedicine);return;}if(btn.dataset.recharge)")
s=s.replace("function render(){recoverStamina(state);normalizeDaily(state);", "function render(){recoverStamina(state);recoverInnerPower(state);normalizeDaily(state);")
old="setInterval(()=>{const before=state.player.stamina;recoverStamina(state);if(state.player.stamina!==before){saveState(state);renderResources();}},30000);"
new="setInterval(()=>{const beforeStamina=state.player.stamina,beforeTick=Number(state.innerPower?.lastTick||0);recoverStamina(state);recoverInnerPower(state);const changed=state.player.stamina!==beforeStamina||Number(state.innerPower?.lastTick||0)!==beforeTick;if(changed){saveState(state);renderResources();if(currentPage==='growth'&&selectedGrowthTab==='innerPower')renderGrowth();}},30000);"
assert old in s
s=s.replace(old,new)
p.write_text(s)
bp=Path('src/battle.js');b=bp.read_text();b=b.replace("initialRage:rageEffect?.initialRage||0","initialRage:(rageEffect?.initialRage||0)+Number(s.initialRage||0)");b=b.replace("return {amount:Math.max(1,Math.round(base*multiplier*variance*(crit?1.5:1))),miss:false,crit};","const bonus=1+Number(attacker.damageBonus||0)/100,reduction=Math.max(.2,1-Number(target.damageReduction||0)/100); return {amount:Math.max(1,Math.round(base*multiplier*variance*(crit?1.5:1)*bonus*reduction)),miss:false,crit};");bp.write_text(b)
ip=Path('index.html');ip.write_text(ip.read_text().replace('单机精简版 · V0.4','单机精简版 · V0.5'))
sp=Path('sw.js');w=sp.read_text().replace("xinyitian-v0.4.0","xinyitian-v0.5.0");w=w.replace("  './src/kungfu.js',\n","  './src/kungfu.js',\n  './src/innerpower.js',\n");sp.write_text(w)
print('V0.5 patch applied')